- api/config/settings.py
- api/users/serializers.py
- api/users/utils.py
**유형 (Type):**
<br><br>
- 로그인 시 JWT 엑세스토큰 및 리프레시토큰 발급 코드 추가
- 토큰 검증 코드 추가
<br><br>
<br><br>
<br><br>
<br><br>
> Feat: 로그인 시 JWT 토큰 발급

- api/config/settings.py
- docker-compose.yml
- poetry.lock
- pyproject.toml
**유형 (Type):**
<br><br>
<br>RDS 세팅 및 연결 aws는 포스트그레 16.3버전, 현재 세팅 버전은 15.7 둘이 호환되는거 확인 완, 포에트리에 db 연결 라이브러리 추가 완료, 도커 빌드후 run 했을때 db connection accept 확인 완료. <br>
<br>api/manage.py 경로 확인 필요. 해당 경로로 파일을 못찾아서 app 컨테이너 구동 불가 <br>
<br><br>
<br><br>
> Rds_settings

- .github/ISSUE_TEMPLATE/feature_request.md
- api/config/settings.py
- docker-compose.yml
- poetry.lock
- pyproject.toml
**유형 (Type):**
<br><br>
<br>유저의 미디어 파일 업로드와 가공을 위한 S3버킷 생성과 연결<br>
<br>현재 개발환경이라 s3커스텀도메인이 직접 S3url로 설정되어있습니다. 주석처리 되어있는 것은 배포때 올라갈 클라우드프론트로 배포되어있는 커스텀 도메인으로 개발환경에서 연결시 비용부과가 될수 있어 주석처리 해두었습니다. 최종 배포 혹은 테스트때 주석해제 필요<br>
<br><br>
<br><br>
> S3버킷 세팅 및 연결

- .github/workflows/checks.yml
- api/config/settings.py
**유형 (Type):**
<br><br>
<br>ECS의 로컬과 배포 환경의 차이로 더이상 배포가 늦어지면 차질이 생기므로 우선 테스트로 EC2 올립니다.<br>
<br><br>
<br><br>
<br><br>
> 배포테스트환경 세팅(EC2버전)

- api/users/views/user_auth_view.py
**유형 (Type):**
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
> token refresh view 수정

- api/comments/urls.py
- api/users/urls/auth_urls.py
- api/users/views/user_auth_view.py
**유형 (Type):**
<br><br>
<br>기존 소셜 로그인으로 기반하여 만들어진 인증인가 방식인 (CookieJWTAuthentication)와 hoonsuauthclass의 방식을 일반로그인에서는 제거, 인증인가는 따로 설정하지 않고 BasicAuthentication사용, 또한 토큰의 방식은 utils.GeneralAuthClass 사용
일반로그인 가능 기존 로그인 불가 시나리오 해결
url규칙화를 위해 모든 엔드포인트 마무리 '/'로 설정<br>
<br><br>
<br><br>
<br><br>
> general login fix

- api/articles/tests/test_article_crud.py
- api/articles/tests/test_article_reaction.py
- api/comments/serializers.py
- api/comments/tests/test_comment_crud_views.py
- api/comments/tests/test_comment_reaction_views.py
- api/comments/views/comment_reaction_views.py
- api/notifications/tests.py
- api/profiles/serializers.py
- api/profiles/tests.py
- api/profiles/views/profile_auth_views.py
- api/users/serializers.py
- api/users/tests.py
- api/users/urls/auth_urls.py
- api/users/views/user_auth_views.py
- api/users/views/user_crud_views.py
**유형 (Type):**
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
> Hotfix/nickname, user, tests

- .github/workflows/checks.yml
**유형 (Type):**
<br><br>
<br><br>
<br>깃액션 테스트 결과 빨리 내보내게 하기위해 keepdb 삭제<br>
<br><br>
<br><br>
>  --keppdb 삭제

- api/comments/serializers.py
- api/comments/views/comment_reaction_views.py
- api/config/settings.py
- api/profiles/serializers.py
**유형 (Type):**
<br><br>
<br>user_info에 user_id값 추가, comment에 댓글을 두번이상 작성할 경우의 에러메세지 표출<br>
<br><br>
<br><br>
<br><br>
> user_info_comment_edit

- api/articles/serializers.py
- api/comments/serializers.py
유저 프로필 이미지와 훈수레벨 추가
**유형 (Type):**
<br><br>
<프론트 요청>
전체 or 특정 게시글 및 댓글 조회 시 필드에 유저 프로필 이미지와 훈수 레벨 추가
<br><br>
<br><br>
<br><br>
<br><br>
> 게시글 및 댓글 조회 시 필드 추가

- api/comments/views/comment_reaction_views.py
**유형 (Type):**
<br><br>
<프론트 요청>
댓글 채택 api 요청 시 응답값으로 해당 댓글 내용 말고 생성된 ai답변 으로 수정
댓글 채택 뷰 수정했슴니다 !!
<br><br>
<br><br>
<br><br>
<br><br>
> 댓글 채택 시 응답값 변경

- api/comments/views/comment_reaction_views.py
**유형 (Type):**
<br><br>
<프론트 요청>
- 응답값 AiHunsuDetail api 랑 똑같이 변경
<br><br>
<br><br>
<br><br>
<br><br>
> 댓글 채택 응답값 수정

- locust/locustfile.py
**유형 (Type):**
<br><br>
<br>테스트용 db 새로 만들어두었습니다. (rds), 테스트 스크립트를 짜두었습니다. 
기존 스크립트는 같은 닉네임과 같은 정보를 가진 유저가 동시접속하는 상황이라 다른 유저 정보를 가진 유저들이 생성되게 세팅 
우선 1차로 로컬에서 스크립트가 돌아가는지 확인후 이후에 ec2에 올려서 부하 테스트 진행하면서 모니터링 하겠습니다. <br>
<br><br>
<br><br>
<br><br>
> locust_setting

- locust/locustfile.py
**유형 (Type):**
<br><br>
<br>locust 테스트중 프로필 관련 테스트시 쿠키 인증을 헤더부분에 넣는 과정 추가, 해당 사용자의 프로필에 접속하고 해당 사용자의 프로필을 수정하도록 쿠키를 set 로그인 실패시 쿠키 초기화. 기존 단위테스트와 다르게 시나리오 테스트 이기때문에 포스트맨 호출 하는 것 처럼 헤더에 쿠키 인증 작업을 넣는 스크립트를 짜야함. 유념 하시길 바랍니당 ><<br>
<br><br>
<br><br>
<br>**테스트 돌릴때 꼭 해야할일** 
1. db가 배포 db인지 아니면 test db인지 env에서 확인하기
2. host가 app인지 확인하기<br>
> profile_anonymous

- api/comments/serializers.py
**유형 (Type):**
<br><br>
<프론트 요청 사항>
댓글 작성 api 응답값 유저정보에 유저 프로필 이미지 추가
-> 시리얼라이저 수정
<br><br>
<br><br>
<br><br>
<br><br>
> 댓글 생성 시 응답값에 프로필이미지 추가

- api/articles/urls.py
- api/articles/views/article_reaction_views.py
- api/comments/urls.py
- api/comments/views/comment_crud_views.py
- api/comments/views/comment_reaction_views.py
**유형 (Type):**
<br><br>
<br>댓글의 상위 5개를 도움이 돼요 순으로 list응답합니다.<br>
<br><br>
<br><br>
<br><br>
> comment_toplist

- api/comments/views/comment_reaction_views.py
**유형 (Type):**
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
> comment_top

- api/reports/views.py
**유형 (Type):**
<br><br>
한 사용자가 같은 게시물이나 댓글을 반복적으로 신고할수없는 로직이 없어서 추가했습니다
<br><br>
<br><br>
<br><br>
<br><br>
> 중복 신고 금지 로직 추가

- api/comments/serializers.py
**유형 (Type):**
<br><br>
comment serializer 중 UserCommentListSerializer 필드에 user_profile_image가 생성되어 유저 프로필 조회 api 호출 시 오류 발생
-> 해당 필드 삭제
* 다른 api 호출 시 문제 없는 것 확인 !!
<br><br>
<br><br>
<br><br>
<br><br>
> comment 시리얼라이저 수정

- api/articles/serializers.py
- api/articles/views/article_list_views.py
- api/articles/views/article_reaction_views.py
- api/comments/serializers.py
- api/comments/views/comment_reaction_views.py
- api/profiles/serializers.py
**유형 (Type):**
<br><br>
유저 프로필 업데이트 중 태그 수정할때 빈 배열 []을 넣으면
응답값은 200 OK 뜨지만 수정 안되고 그대로임
-> 수정 완료
댓글 게시글 정렬 수정
-> 시리얼라이지 meta class에 ordering 추가하는건 실제 정렬 방식에 영향 x
-> view에서 쿼리 가져올때 .order_by("-created_at") 추가해서 최신순으로 정렬
인기게시글, 인기훈수 조회 뷰에 permission_classes = [AllowAny] 추가
-> 비로그인 유저도 볼수있어야하기 때문에 수정했습니다
<br><br>
<br><br>
<br><br>
<br><br>
> 유저 태그 업데이트

- api/articles/tests/test_article_crud.py
**유형 (Type):**
<br><br>
<br>테스트 코드 수정( 기존 게시글 생성과 수정 뷰에서 formdata 형식으로 보내던걸 json으로 코드를 바꾸면서 테스트 코드에도 해당 부분 반영<br>
<br><br>
<br><br>
<br><br>
> article_test_edit

- api/articles/views/article_reaction_views.py
- api/tags/serializers.py
- api/tags/tests.py
**유형 (Type):**
<br><br>
<br>태그 시리얼라이저에서 태그이름삭제<br>
<br><br>
<br><br>
<br><br>
> tag_name, view allowany

- api/users/urls/auth_urls.py
- api/users/views/user_auth_views.py
**유형 (Type):**
<br><br>
<프론트 요청>
유저 로그인 상태 확인하는 api 생성
<br><br>
<br><br>
<br><br>
<br><br>
> 유저 로그인 상태 확인 api

- api/config/settings.py
**유형 (Type):**
<br><br>
액세스토큰 만료시간 1일, 리프레시 토큰 만료시간 7일로 수정
<br><br>
<br><br>
<br><br>
<br><br>
> 토큰 만료시간 수정

- api/comments/serializers.py
**유형 (Type):**
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
> article_top

- api/users/utils.py
**유형 (Type):**
<br><br>
set_cookie에 domain 삭제
<br><br>
<br><br>
<br><br>
<br><br>
> 프론트 로컬 테스트용 쿠키 세팅

- api/notifications/serializers.py
- api/notifications/signals.py
**유형 (Type):**
<br><br>
게시글 id, description, 게시글 제목, 댓글 내용 추가
<br><br>
<br><br>
<br><br>
<br><br>
> notification 수정

- api/articles/s3instance.py
**유형 (Type):**
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
> article_image_delete

- api/articles/s3instance.py
- api/articles/views/article_crud_views.py
**유형 (Type):**
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
> article_image

- api/articles/serializers.py
- api/articles/views/article_crud_views.py
**유형 (Type):**
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
> edit thumbnail

- api/notifications/serializers.py
**유형 (Type):**
<br><br>
알림 description에 유저 닉네임 제거
<br><br>
<br><br>
<br><br>
<br><br>
> 알림 description 수정

- api/articles/views/article_crud_views.py
**유형 (Type):**
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
> edit article_id

- api/reports/views.py
**유형 (Type):**
<br><br>
같은 게시물 or 댓글 중복 신고 시 status 400 -> status 409 conflict 로 수정
<br><br>
<br><br>
<br><br>
<br><br>
> 중복 신고 status 수정

- api/users/views/user_auth_views.py
**유형 (Type):**
<br><br>
일반 로그인 회원가입 및 로그인 시 last_login timezone.now()로 update
<br><br>
<br><br>
<br><br>
<br><br>
> 일반 로그인 last_login update

- locust/locustfile.py
**유형 (Type):**
<br><br>
<br>로커스트 테스트 코드의 동적할당 추가, 이벤트 및 로깅 추가로 상세한 로깅과핸들링 반영
추가 수정 아직 진행해야함<br>
<br><br>
<br><br>
<br><br>
> locust_test_code

- api/notifications/signals.py
**유형 (Type):**
<br><br>
<br>좋아요 두번누르면 취소가 되는데 취소시에도 좋아요가 눌러졌다는 알림이 발송되는 상황수정, 좋아요 취소시 좋아요가 갔던 알림 삭제.<br>
<br><br>
<br><br>
<br><br>
> like_noti_edit

- api/users/models.py
- api/users/views/user_auth_views.py
**유형 (Type):**
<br><br>
<br>회원 탈퇴시 이메일 유효성 검사 삭제. 이미 검토는 토큰으로 인증하므로 별다른 인가 처리 없이 탈퇴 진행<br>
<br><br>
<br><br>
<br><br>
> user_delete

- api/users/views/user_auth_views.py
**유형 (Type):**
<br><br>
<br>비밀번호 재설정 링크 인증후 재설정 APiConfirmation시에 credential 에러 비밀번호를 재설정해야하는 부분이므로 allowany로 수정<br>
<br><br>
<br><br>
<br><br>
> pwd_allowany

- api/users/serializers.py
- api/users/urls/auth_urls.py
- api/users/views/user_auth_views.py
**유형 (Type):**
<br><br>
<br>닉네임과 아이디의 검증에 대한 APi를 추가하였습니다. 이메일 검증의 경우 해당부분에 대해 응답 값에 코드를 명시하였습니다. <br>
<br><br>
<br><br>
<br><br>
> username_nickname_validation

- api/users/serializers.py
**유형 (Type):**
<br><br>
<br>닉네임과 아이디 중복성 검사 장고 기본 중복검사 해제_해당부분에 대해 프론트에서 처리 예정<br>
<br><br>
<br><br>
<br><br>
> validation_free

- api/users/serializers.py
- api/users/urls/auth_urls.py
- api/users/views/user_auth_views.py
**유형 (Type):**
<br><br>
<br>기존 서버에서 처리하던 이메일 중복검사에 대해  중복에 대한 유무를 가입전에 알게하기위해 , 클라이언트를 위한 이메일 중복 검사 APi 추가 , 회원가입 API의 경우 이메일, 닉네임, 아이디에 대한 validation_deactivate처리<br>
<br><br>
<br><br>
<br><br>
> validation_free_email

- api/notifications/signals.py
**유형 (Type):**
<br><br>
<br>알림의 중복성을 방지하기위해 알림을 생성하기 전에 동일한 조건의 알림(recipient, verb, object_id, content_type)이 이미 존재하는지 확인, transaction.on_commit 사용해 데이터베이스 트랜잭션이 완료된 후 알림을 생성하여, 데이터 무결성 보장(해당부분 사용자 댓글 채택 issue에 적용한 과거 있음)<br>
<br><br>
<br><br>
<br><br>
> filtering_notification

- api/notifications/signals.py
**유형 (Type):**
<br><br>
신고가 db에 커밋된 후 알림 생성되도록 transaction.on_commit() 추가
<br><br>
<br><br>
<br><br>
<br><br>
> admin 알림 트랜젝션

- api/articles/serializers.py
- api/articles/views/article_list_views.py
**유형 (Type):**
<br><br>
시리얼라이저에 로그인 여부 status와 좋아요 여부 like 추가
<br><br>
<br><br>
<br><br>
<br><br>
> 전체게시글 조회 시 좋아요 여부 확인

- api/articles/serializers.py
- api/articles/views/article_reaction_views.py
**유형 (Type):**
<br><br>
제가 다른 api 건드렸다가
top article, profile api 오류가 떠서 고쳤습니다...
<br><br>
<br><br>
<br><br>
<br><br>
> top article, profile api 오류 

- api/articles/serializers.py
**유형 (Type):**
<br><br>
request가 None이거나, 인증되지 않은 사용자일 경우 수정
> dploy 12.5

- api/users/utils.py
- api/users/views/user_auth_views.py
**유형 (Type):**
<br><br>
<br>토큰이름 hunsu_어쩌구로 바꿈, 다른 사이트 들어갔다가 훈수왕 들어오면 토큰이름이 겹쳐서... ㅎㅎ<br>
> change_token_name

- api/profiles/serializers.py
**유형 (Type):**
<br><br>
- 게시글 좋아요 추가
- 댓글 도움이 돼요, 도움이 안돼요 수 추가
<br><br>
<br><br>
<br><br>
<br><br>
> 프로필 시리얼라이저 수정

- api/articles/signals.py
- api/articles/tests/test_article_crud.py
- api/articles/views/article_list_views.py
- api/profiles/tests.py
- api/reports/tests.py
**유형 (Type):**
<br><br>
<br>게시글 조회 페이지네이션 적용, 한페이지당 12개 게시글 적용, 장고 기본 캐싱 적용 15분동안 캐시저장, 서버 응답속도  첫 응답이후 100ms 이하로 줄어듬(첫응답 소요시간 600~1000ms), 게시글 생성, 수정, 삭제시에 캐시 무효화 signal 생성, 캐시키의 경우 단일키가 아닌 페이지 네이션이 적용되었기 때문에 각 페이지별 캐시키를 가짐. 무효화는 전체 페이지(현재는 100까지) 무효화로 설정
추후 redis 세팅해서 전체 무효화 delete 메서드로 변경예정. <br>
> article_list_cashing
